services:
  project-core:
    container_name: project-core
    deploy: {}
    runtime: nvidia
    image: denden047/project-core
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:12.1.0-devel-ubuntu20.04
        - PYTHON_VERSION=3.11
        - FORCE_CUDA=1
        - UID=1000
        - GID=1000
        - USER_NAME=ubuntu
        - GROUP_NAME=ubuntu
        - TORCH_CUDA_ARCH_LIST=7.5,8.6
      context: ./
      dockerfile: Dockerfile
    shm_size: "16gb"
    tty: true
    volumes:
      - ../:/home/ubuntu/project
      # - /data/naoya/:/data/
    # ports:
    #   - 8000:8000
